name: rusty_controller
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.3
  logger: ^1.1.0
  graphql_flutter: ^5.1.0
  get_it: ^7.2.0
  rate_limiter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
