[package]
name = "rusty_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
# Log
log = "0.4"
env_logger = "0.9.0"

# HID magic
hidapi = "1.3.3"

# Colors
palette = "0.6"

# Async
tokio = { version = "1.17.0", features = ["net", "sync", "macros", "rt-multi-thread"] }

# GraphQL
actix-web = "4"
actix-web-lab = "0.16.1"
actix-cors = "0.6.0"
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
juniper = "0.15.9"
