version: "3"

name: grafana

networks:
  grafana:

services:
  loki:
    # This version is used because the newer ones break on ARM
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'

  promtail:
    image: grafana/promtail:2.7.4
    command: -config.file=/mnt/config/config.yaml
    volumes:
      - /var/log/rusty-controller:/var/log/rusty-controller
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      resources:
        limits:
          cpus: '0.5'

  process-exporter:
    ports:
      - "9256:9256"
    privileged: true
    volumes:
      - /proc:/host/proc
      - "./config:/config"
    image: ncabatoff/process-exporter
    command: --procfs /host/proc -config.path /config/process-exporter.yaml
    deploy:
      resources:
        limits:
          cpus: '0.5'

  prometheus:
    image: prom/prometheus:v2.24.0
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_DATABASE_WAL: true
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '1.0'

volumes:
  loki-data:
  prom-data:
  grafana-data:
