version: "3"

name: grafana

networks:
  grafana:

services:
  loki:
    # This version is used because the newer ones break on ARM
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'

  promtail:
    image: grafana/promtail:2.7.4
    command: -config.file=/mnt/config/config.yaml
    volumes:
      - ./config/promtail.yaml:/mnt/config/config.yaml
      - /var/log/rusty-controller:/var/log/rusty-controller
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'

  prometheus:
    image: prom/prometheus:v2.24.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - grafana
    deploy:
      resources:
        limits:
          cpus: '1.0'

volumes:
  loki-data:
  prom-data:
  grafana-data:
