name: Build

on:
  push:
    # On main, it's the build and release that will run
    branches-ignore: [ "main" ]

jobs:
  server:
    runs-on: ubuntu-latest
    
    env:
      CARGO_TERM_COLOR: always

    defaults:
      run:
        shell: bash
        working-directory: ./server

    steps:
    - uses: rui314/setup-mold@v1

    - uses: actions/checkout@v3
    
    - name: 🌱 - Install dependencies
      run: sudo apt-get update; sudo apt-get install -y libudev-dev libsystemd-dev libusb-1.0-0-dev
    
    - name: 🧯 - Check for compile errors
      run: cargo check
    
    - name: 🧐 - Lint check
      run: cargo clippy -- -D warnings

    - name: 🔨 - Build
      run: cargo build

    - name: 🧪 - Run tests
      run: cargo test --verbose
  
  app:
    runs-on: ubuntu-latest
    
    defaults:
      run:
       shell: bash
       working-directory: ./app

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 🌱 - Get dependencies
        run: flutter pub get

      - name: ⭐ - Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: 🧐 - Analyze project source
        run: dart analyze --fatal-infos
    
      - name: 🧪 - Run tests
        run: flutter test
        
      - name: 🔨 - Build
        run: flutter build appbundle
